# Permalinks
relative_permalinks: false

# Setup
title:            Sean Purcell
tagline:          Some of the all of the things
url:              http://seanp97.com
paginate:         3
baseurl:          /
author:
  name:           Sean Purcell
  email:          seanpurcell97@gmail.com

# Custom vars
version:          1.0.0
blogurl:          /blog/
permalink:        /blog/:year/:month/:day/:title/
paginate_path:    /blog/page:num

pages_list:
  About: '/about'
  Projects: '/projects'
  Resume: '/resume.pdf'

github:           https://github.com/iburinoc
email:            me@seanp97.com
highlighter:      pygments
